### PR TITLE
Multiple app bug

### LINKED ISSUE #89: Multiple applications are being created at once

### PR DESCRIPTION
**Pull request by katherinetucker**
#89: will only call create app once now, fixed so viewing app after submission won't create new one

closes #89

### CODE REVIEW

File: app/main/controllers/applicationInformation-ctrl.js [hunk 1]
```diff
@@ -2,9 +2,11 @@
 angular.module('myApp')
 .controller('ApplicationInformationCtrl', function ($scope, $state, $rootScope, $stateParams, DataService, $location) {
   if(!$stateParams.appId) {
```
Comment (ryanturner) [inline app/main/controllers/applicationInformation-ctrl.js]: do what you do
